### ISSUE TITLE
Create self-hosting guide for Fly.io

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev-docs#5]
We currently have a repo with a README with instructions for deploying a self-hosted version of Trigger.dev to fly.io, but I'd like a dedicated guide in the docs (under the Self hosted sidebar item)

**Comment by Ashutosh-Bhadauriya** [comment]
@ericallam can you please assign this to me

**Comment by Ashutosh-Bhadauriya** [comment]
@ericallam just raised a pr for this issue, please let me know your opinion. Thanks!
