### ISSUE TITLE
Create a self-hosting guide (similar to our existing Fly.io guide) for Render.com

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev-docs#8]
/bounty $100

The fly.io guide links to our [fly.io](https://github.com/triggerdotdev/fly.io) repo, if it makes sense to also have a starting repo for Render.com, then part of this issue will be supplying that repo (you can push it to your account and then we can either fork it or you can transfer it over to us, if you don't want to keep it on your account).

**Comment by Ashutosh-Bhadauriya** [comment]
@ericallam just created a pr please let me know your thoughts. Thanks!
